### ISSUE TITLE
Link State View UI Issues

### ISSUE THREAD

**Issue by mnanduri** [OpenBMP/docker#11]
Couple of issues. 

1. Link State View not showing some of the TE attributes even though those are in the database for example Reserved BW/Available BW 
2. Topology table not displaying any info

Please let me know what additional info is required.

**Comment by TimEvens** [comment]
@mnanduri, 

1.  Will fix that in the UI. 
2. Topology requires the stored procedures the run the SPF... Those aren't part of open source right now, but I have emailed you a copy of those.

**Comment by bugtoo** [comment]
@TimEvens I would like to test the Topology feature as well: is it possible to have the SPF stored procedure? Thanks!

**Comment by mnanduri** [comment]
Thanks Tim. You provided the stored procedure and it working now, thanks. Closing it.
