### ISSUE TITLE
docker aio fails to start tomcat7

### ISSUE THREAD

**Issue by psyc0** [OpenBMP/docker#5]
when running the container without -d I see that tomcat fails to start, also trying to restart the service manually fails with the same error

root@b8d7896707e1:/tmp# service tomcat7 status
- Tomcat servlet engine is not running.
  root@b8d7896707e1:/tmp# service tomcat7 start 
- Starting Tomcat servlet engine tomcat7
  ...fail!

root@b8d7896707e1:/tmp# tail -f /var/log/tomcat7/catalina.out
Sep 24, 2016 9:59:45 AM org.apache.catalina.core.StandardService stopInternal
INFO: Stopping service Catalina
Sep 24, 2016 9:59:45 AM org.apache.catalina.loader.WebappClassLoader clearReferencesJdbc
SEVERE: The web application [/db_rest] registered the JDBC driver [org.mariadb.jdbc.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Sep 24, 2016 9:59:45 AM org.apache.catalina.loader.WebappClassLoader clearReferencesThreads
SEVERE: The web application [/db_rest] appears to have started a thread named [PoolCleaner[1695611352:1474711183076]] but has failed to stop it. This is very likely to create a memory leak.
Sep 24, 2016 9:59:45 AM org.apache.coyote.AbstractProtocol stop
INFO: Stopping ProtocolHandler ["http-bio-8001"]
Sep 24, 2016 9:59:45 AM org.apache.coyote.AbstractProtocol destroy
INFO: Destroying ProtocolHandler ["http-bio-8001"]

**Comment by Matvey-Kuk** [comment]
Thank you! 

Reproduced. Looks like Tomcat starts properly and fails to restart. I'll return back to this a little bit later.

**Comment by Matvey-Kuk** [comment]
@psyc0 looks like everything is working as expected. This entry in log doesn't mean smth goes wrong. @TimEvens I think issue can be closed.

How to verify if everything works.

1) Execute:
```
    docker run -d --name=openbmp_aio \
         -e API_FQDN=localhost \
         -v /var/openbmp/mysql:/data/mysql \
         -p 3306:3306 -p 2181:2181 -p 9092:9092 -p 5000:5000 -p 8001:8001 \
         openbmp/aio
```

2) Setup your router to produce dmp data to host:5000. 

3) Go to http://docker_host:8001/db_rest/v1/routers

> Username: **openbmp**
> Password: **CiscoRA**

4) Dive into your data =) More information about API: https://github.com/OpenBMP/db_rest

**Comment by TimEvens** [comment]
@psyc0 , it's a false error message.  We'll update the unit script to report correctly. Thanks.

**Comment by TimEvens** [comment]
this has been resolved.
