### ISSUE TITLE
Cannot Login to  openbmp_ui  web interface.

### ISSUE THREAD

**Issue by Slapper** [OpenBMP/docker#8]
Hello,

We have just install openbmp_ui docker for testing purposes, but when when we are trying to login ( Username: openbmp Password: CiscoRA ) we are getting the following error : **Authentication service is unreachable** .
We have also running openbmp_aio docker on the same host with all required services ( mysql, kafka, collector ).  Which service is the Authentication service ? Is it MySQL ? Can we change somehow default username/pass ?

Thanks in advance.

Kind Regards,
Miltos

**Comment by Slapper** [comment]
You can close this issue. The problem was the 8001 port was blocked in the firewall.

Thanks!

**Comment by TimEvens** [comment]
thanks.
